-- AlterTable
ALTER TABLE `Device` MODIFY `mobile` INTEGER NULL DEFAULT 0,
    MODIFY `tablet` INTEGER NULL DEFAULT 0,
    MODIFY `desktop` INTEGER NULL DEFAULT 0,
    MODIFY `eReader` INTEGER NULL DEFAULT 0,
    MODIFY `unknown` INTEGER NULL DEFAULT 0;
